#ifndef DEFINES_HPP
#define DEFINES_HPP

#define TILE_SIZE 32.f
#define WINDOW_WIDTH 1024.f
#define WINDOW_HEIGHT 720.f
#define ORTHO_WIDTH (WINDOW_WIDTH / TILE_SIZE)
#define ORTHO_HEIGHT (WINDOW_HEIGHT / TILE_SIZE)

#endif /* ifndef DEFINES_HPP */
